title: "Kim Sang-hyeob's Tech Blog"
description: "Developer diary and tech blog; research reviews and portfolio."
url: "https://kim-sang-hyeob.github.io"

remremote_theme: "mmistakes/jekyll-theme-basically-basic@1.4.5"
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
author:
  name: Kim Sang-hyeob
  avatar: ""
  bio: "Developer and researcher. Sharing my tech journey."
  links:
    - label: "GitHub"
      url: "https://github.com/kim-sang-hyeob"
github_username: "kim-sang-hyeob"
