title: "Kim Sang-hyeob's Tech Blog"
description: "Developer diary and tech blog; research reviews and portfolio."
url: "https://kim-sang-hyeob.github.io"
baseurl: ""
remote_theme: mmistakes/minimal-mistakes@4.27.3
minimal_mistakes_skin: "mint"
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache
author:
  name: Kim Sang-hyeob
  avatar: ""
  bio: "Developer and researcher. Sharing my tech journey."
  links:
    - label: "GitHub"
      url: "https://github.com/kim-sang-hyeob"
github_username: "kim-sang-hyeob"
