
title: "Kim Sang-hyeob's Tech Blog"
tagline: "Developer diary and tech blog; research reviews and portfolio."
description: "Developer diary and tech blog; research reviews and portfolio."
lang: ko
timezone: Asia/Seoul
url: "https://kim-sang-hyeob.github.io"
baseurl: ""
remote_theme: cotes2020/jekyll-theme-chirpy@v7.3.1
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
github:
  username: kim-sang-hyeob
social:
  name: Kim Sang-hyeob
  links:
    - https://github.com/kim-sang-hyeob
toc: true
